gui:
  theme:
    activeBorderColor:
      - "#00bb00"
      - bold
    selectedLineBgColor:
      - "#0000ee"
customCommands:
  - key: "W"
    command: git commit --no-verify
    context: "global"
    subprocess: true
